[package]
name = "gpts-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Cargo.toml
[build-dependencies]
cmake = "^0.1"
bindgen = "^0.65.1"