version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "ggerganov/llama.cpp"
      - dependency-name: "saharNooby/rwkv.cpp"
    schedule:
      interval: "daily"