[package]
name = "rwkv-sys"
version = "0.1.0"
edition = "2021"
description = "Raw bindings (i.e. bindgen output) for the rwkv.cpp library."
license = "MIT"

# Cargo.toml
[build-dependencies]
cmake = "0.1"
bindgen = "^0.65.1"