[package]
name = "notgpt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rwkv = {path = "../rwkv"}
anyhow = "^1.0.71"
tokenizers = "^0.13.3"
log = "0.4"
env_logger = "^0.10"
